POST  http://localhost:3000/api/v1/articles HTTP/1.1
content-type: application/json

{
    "title": "Новый title",
    "announcement": "Новый анонс",
    "mainText": "Новый текст",
    "categories": [1, 2]
}